### PR TITLE
Amend wellbeing box on homepage and wellbeing main page

### PR DESCRIPTION
**Pull request by mark-pkgflow**
## Changes

- [ ] wellbeing box on the homepage
- [ ] the wellbeing page:
  - [ ] intro line under the page title
  - [ ] the ‘how to’ box
  - [ ] the ‘promote wellbeing…’ section to the right hand side of the page

image

### CODE REVIEW

**Comment by mark-pkgflow** [comment]
[Amend wellbeing box on homepage and wellbeing main page](https://trello.com/c/iuWVCWdQ/409-amend-wellbeing-box-on-homepage-and-wellbeing-main-page)

**Comment by claire-hughez** [comment]
Thanks Mark.

Screenshot 2024-03-26 at 10 49 27
The staff wellbeing box and the workload reduction toolkit boxes are now different sizes on the homepage. Is there a way we can make them the size? Do we need to add more context to the workload reduction toolkit box to balance it out? 

The staff wellbeing page looks great.

Screenshot 2024-03-26 at 10 50 43
Just thinking, should we change this so the links are before the text explaining what they are? This better matches the boxes we have on the service and the links on the mental health page.

**Comment by lauren-oseni-2** [comment]
For the share your ideas & feedback stuff on the side, the links are below the body text. So I'm wondering if having links above body text for this section (Promote wellbeing and flexible working in your school) will look odd

**Comment by ashleighk27** [comment]
I agree with your comment Claire about trying to make the homepage boxes more symmetrical. 
Re changing the ordering of the link and one-liners on the right hand side, the reason I structured them like this is because the 'share your ideas' and 'feedback' sections underneath follow the same format, with the explanation above the link.

**Comment by claire-hughez** [comment]
Thanks both!

Sounds good to me to leave the box on the right then as is.

For the homepage wellbeing box, @mark-pkgflow shout if we need design help in fixing this.

**Comment by lauren-oseni-2** [comment]
Image 26-03-2024 at 12 04

@mark-pkgflow I've updated the style guide in figma to help with the sizing and spacing if you'd find that helpful :)

**Pull request merged**
