### PR TITLE
[407] Fix spacing and update content on homepage

### PR DESCRIPTION
**Pull request by AbigailMcP**
## Changes in this PR

- Fix spacing around homepage tiles
- Update content on wellbeing tile
- Ensure homepage tiles stay the same size with different length content
- Fix spacing on Explore all resources section
- Fix spacing on full-width 'Share your ideas' and 'Help improve our service' section
- Fix spacing around Workload reduction toolkit 'Use the toolkit' title

## Guidance to review

- Compare pages to screenshots on Trello ticket: https://trello.com/c/F2Ov4Eeg/407-adjust-padding-and-spacing-for-the-main-landing-page-toolkit-landing-page
- **IMPORTANT** - check the page on mobile to check things still look ok!!

Screenshot 2024-03-26 at 14 27 01

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[Adjust padding and spacing for the main landing page + toolkit landing page](https://trello.com/c/F2Ov4Eeg/407-adjust-padding-and-spacing-for-the-main-landing-page-toolkit-landing-page)

**Review by mark-pkgflow — APPROVED** [review]
LGTM on mobile too

**Comment by lauren-oseni-2** [comment]
All looks good to me! just one small snag: can we reduce the font size for the 'explore all resources' text in the blue button for mobile? It seems a little big to me - should be 19px!

**Comment by lauren-oseni-2** [comment]
Oh and i think the padding around the 'share your ideas + feedback' bit needs adjusting! Should have padding of 65px on top: 
Image 20-03-2024 at 16 04 (1)

**Comment by AbigailMcP** [comment]
> Oh and i think the padding around the 'share your ideas + feedback' bit needs adjusting! Should have padding of 65px on top and 75px on bottom.

I thought they were actually.. let me take another look.

**Pull request merged**
