### PR TITLE
Add resource images for presentations and templates

### PR DESCRIPTION
**Pull request by mark-pkgflow**
Card: [Add all the screenshots for presentations or templates to the service](https://trello.com/c/HYbYrxYb)

## Summary

Adding al the preview images for the downloadable files on the service.

image

## Guidance to review

Check:

- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/behaviour-management/review-and-streamline-behaviour-management
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/communications/review-and-streamline-communications
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/curriculum-planning-and-delivery/review-and-streamline-lesson-planning
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/data-management/review-and-streamline-data-management
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-and-streamline-feedback-and-marking
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/address-workload-issues/feedback-and-marking/review-marking-practice-with-an-impact-matrix
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/evaluate-workload-measures/structured-conversations-with-staff
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/evaluate-workload-measures/update-your-workload-action-plan
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/act-on-your-staff-workload-survey
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/create-an-action-plan-to-reduce-workload
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/have-structured-conversations-to-identify-issues
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/plan-your-yearly-calendar
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/prioritise-change-using-impact-graphs
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/identify-workload-issues/share-progress-with-staff
- [ ] https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/evaluate-workload-measures/evaluate-progress-with-staff

### CODE REVIEW

**Comment by mark-pkgflow** [comment]
[Add all the screenshots for presentations or templates to the service](https://trello.com/c/HYbYrxYb/304-add-all-the-screenshots-for-presentations-or-templates-to-the-service)

**Comment by claire-hughez** [comment]
Hey! Generally looks really good and fits well. Just 1 missing screenshot:

https://deploy-preview-90--iwwss-review.netlify.app/workload-reduction-toolkit/evaluate-workload-measures/evaluate-progress-with-staff/ should have the same screenshot as Share progress with staff - sorry this is missing from the ticket

@mark-pkgflow apart from the staff workload survey, is there any way to easily tell if we're missing any other screenshots now? :)

**Comment by mark-pkgflow** [comment]
> @mark-pkgflow apart from the staff workload survey, is there any way to easily tell if we're missing any other screenshots now? :)

@claire-hughez we can search the code for `preview-placeholder.jpg`

**Review by AbigailMcP — APPROVED** [review]

**Comment by mark-pkgflow** [comment]
> > @mark-pkgflow apart from the staff workload survey, is there any way to easily tell if we're missing any other screenshots now? :)
> 
> @claire-hughez we can search the code for `preview-placeholder.jpg`

This is what is left...

image

**Comment by claire-hughez** [comment]
Awesome! Looks like they're all sorted then and we're good to go. Thanks Mark.

**Pull request merged**
